name: Java Build Workflow

on:
  push:
    branches:
      - main
      - Work
jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Build and Test
        run: |
          javac -d out $(find . -name "*.java")
          java -cp out MainClass
