name: Java Build Workflow

on:
  push:
    branches:
      - Main
      - Release-branch
      - Mador-Branch
      - Daivakai
      - Daivakai-branch
      - Csökönyi-branch
      - Csomos
      - HerrSchnitzer-patch-1

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Grant execute permissions
        run: chmod +x compile.sh run.sh test.sh

      - name: Compile
        run: ./compile.sh

      - name: Run (with exit)
        #run: ./run.sh | echo "exit"
        run: ./run.sh | echo "5"
        run: echo "5" | ./run.sh 

      # - name: Test
      #   run: echo "50" | ./test.sh