name: Java Build Workflow

on:
  push:
    branches:
      - main

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Grant execute permissions
        run: chmod +x compile.sh run.sh test.sh

      - name: Compile
        run: ./compile.sh

      - name: Run
        run: ./run.sh

      - name: Test
        run: ./test.sh